### ISSUE TITLE
Console should not steal focus

### ISSUE THREAD

**Issue by ccoenen** [Dreamscapes/atom-ide-mocha#9]
**Describe the bug**
When I save a document and my tests are run, the console pops up and steals my focus

**To Reproduce**
1. have something in the background running your tests, i.e. `nodemon -w test --exec mocha ...`
1. save the file you're working on
1. have your focus set to the console by force

**Expected behavior**
I would like to have (at least) the option to not have this seal my focus. I save this file every few seconds and I don't want to switch back to my editor window manually.

**Desktop (please complete the following information):**
- Atom: 1.36
- ide-mocha: 2.6.0

**Comment by ccoenen** [comment]
I just found the correct option: at the bottom of the plugin's settings is "Open console pane ..." - this will not happen if these are unchecked.

**Comment by robertrossmann** [comment]
Hi! Yes, there’s a setting to make this less obtrusive. 👍 Sometimes you want the console to open and sometimes it just gets in the way. 😇
